FTCApiBundle:
    resource: "@FTCApiBundle/Controller/"
    type:     annotation
    prefix:   /

FTCCodeBundle:
    resource: "@FTCCodeBundle/Controller/"
    type:     annotation
    prefix:   /

FTCWebBundle:
    resource: "@FTCWebBundle/Controller/"
    type:     annotation
    prefix:   /

#DMSLauncherBundle:
#    resource: "@DMSLauncherBundle/Controller/"
#    type:     annotation
#    prefix:   /

FTCAuthBundle:
    resource: "@FTCAuthBundle/Controller/"
    type:     annotation
    prefix:   /

# FOS User Bundle #
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
