services:
    ftc_web.twig.extension.security:
        class: FTC\Bundle\WebBundle\Twig\Security\SecurityExtension
        arguments:
            context: @security.context
        tags:
            -  { name: twig.extension }

    ftc_web.twig.extension.date:
        class: FTC\Bundle\WebBundle\Twig\Date\DateExtension
        tags:
            -  { name: twig.extension }

    ftc_web.listener.notification:
        class: FTC\Bundle\WebBundle\Listener\NotificationListener
        arguments:
            templating: @templating
            mailer: @mailer
        tags:
            - { name: kernel.event_subscriber }
