<?php

namespace FTC\Bundle\CodeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CodeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeEntryRepository extends EntityRepository
{

    public function getLatest($max = 10)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->orderBy('e.dateSubmited', 'DESC');
        $qb->setMaxResults($max);

        return $qb->getQuery()->getResult();
    }

    public function getUserEntries($user)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere('e.author = ?0');

        $qb->setParameter(0, $user);
        $qb->orderBy('e.id', 'DESC');

        return new ArrayCollection($qb->getQuery()->getResult());
    }
}
