<?php

namespace FTC\Bundle\CodeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CodeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeEntryRepository extends EntityRepository
{

    public function getLatest($max = 10)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->orderBy('e.dateSubmited');
        $qb->setMaxResults($max);

        return $qb->getQuery()->getResult();
    }

}