<?php

namespace FTC\Bundle\CodeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getUserComments($user)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->andWhere('c.author = ?0');

        $qb->setParameter(0, $user);

        return new ArrayCollection($qb->getQuery()->getResult());
    }

}